### ISSUE TITLE
New users aren't moved from waitingQueue to activeUsers

### ISSUE THREAD

**Issue by ryannmcq** [plinko-team/plinko#69]
In rewire-game branch:

On new user event, server incorrectly sets isGameRunning to true, which means fillActiveUsers is never called and user is not moved from queue to active, even if there is space.

**Comment by brankoculum** [comment]
`serverEngine.startGame()` was being called in server.js, so the game started when the server was fired up; it should only start on a 'start game' socket event now and `isGameRunning` should stay false.
